In [1]:
import os
import pandas as pd

# **1. Leitura dos dados**

In [2]:
estados_path = "/home/usuario/Documents/Awari_EngDados/awari-engenharia-de-dados-docker/exercicios/municipios-estados/csv/estados.csv"
cidades_path = "/home/usuario/Documents/Awari_EngDados/awari-engenharia-de-dados-docker/exercicios/municipios-estados/csv/municipios.csv"

In [3]:
df_estados = pd.read_csv(estados_path)
df_cidades = pd.read_csv(cidades_path)

# **2. Criando pastas para cada UF**

In [4]:
unique_states = df_estados['uf'].unique()

base_folder = 'estados'

os.makedirs(base_folder, exist_ok=True)

for state_acronym in unique_states:
    state_folder = os.path.join(base_folder, state_acronym)
    os.makedirs(state_folder, exist_ok=True)
    print(f"Criando pasta para o estado: {state_acronym}")

Criando pasta para o estado: RO
Criando pasta para o estado: AC
Criando pasta para o estado: AM
Criando pasta para o estado: RR
Criando pasta para o estado: PA
Criando pasta para o estado: AP
Criando pasta para o estado: TO
Criando pasta para o estado: MA
Criando pasta para o estado: PI
Criando pasta para o estado: CE
Criando pasta para o estado: RN
Criando pasta para o estado: PB
Criando pasta para o estado: PE
Criando pasta para o estado: AL
Criando pasta para o estado: SE
Criando pasta para o estado: BA
Criando pasta para o estado: MG
Criando pasta para o estado: ES
Criando pasta para o estado: RJ
Criando pasta para o estado: SP
Criando pasta para o estado: PR
Criando pasta para o estado: SC
Criando pasta para o estado: RS
Criando pasta para o estado: MS
Criando pasta para o estado: MT
Criando pasta para o estado: GO
Criando pasta para o estado: DF

# **2. Organizando cidades por estado num único CSV para cada UF**

In [6]:
display(df_estados.head(), df_cidades.head())

   codigo_uf  uf      nome  latitude  longitude regiao
0         11  RO  Rondônia    -10.83     -63.34  Norte
1         12  AC      Acre     -8.77     -70.55  Norte
2         13  AM  Amazonas     -3.47     -65.10  Norte
3         14  RR   Roraima      1.99     -61.33  Norte
4         15  PA      Pará     -3.79     -52.48  Norte

,codigo_ibge,nome,latitude,longitude,capital,codigo_uf,siafi_id,ddd,fuso_horario
0,5200050,Abadia de Goiás,-16.75730,-49.4412,0,52,1050,62,America/Sao_Paulo
1,3100104,Abadia dos Dourados,-18.48310,-47.3916,0,31,4001,34,America/Sao_Paulo
2,5200100,Abadiânia,-16.19700,-48.7057,0,52,9201,62,America/Sao_Paulo
3,3100203,Abaeté,-19.15510,-45.4444,0,31,4003,37,America/Sao_Paulo
4,1500107,Abaetetuba,-1.72183,-48.8788,0,15,401,91,America/Sao_Paulo

In [7]:
df_cidades_estados = pd.merge(df_cidades, df_estados[["codigo_uf", "uf"]], on = ["codigo_uf"], how = 'left')
df_cidades_estados

,codigo_ibge,nome,latitude,longitude,capital,codigo_uf,siafi_id,ddd,fuso_horario,uf
0,5200050,Abadia de Goiás,-16.75730,-49.4412,0,52,1050,62,America/Sao_Paulo,GO
1,3100104,Abadia dos Dourados,-18.48310,-47.3916,0,31,4001,34,America/Sao_Paulo,MG
2,5200100,Abadiânia,-16.19700,-48.7057,0,52,9201,62,America/Sao_Paulo,GO
3,3100203,Abaeté,-19.15510,-45.4444,0,31,4003,37,America/Sao_Paulo,MG
4,1500107,Abaetetuba,-1.72183,-48.8788,0,15,401,91,America/Sao_Paulo,PA
...,...,...,...,...,...,...,...,...,...,...
5565,2933604,Xique-Xique,-10.82300,-42.7245,0,29,3971,74,America/Sao_Paulo,BA
5566,2517407,Zabelê,-8.07901,-37.1057,0,25,542,83,America/Sao_Paulo,PB
5567,3557154,Zacarias,-21.05060,-50.0552,0,35,2973,18,America/Sao_Paulo,SP
5568,2114007,Zé Doca,-3.27014,-45.6553,0,21,1287,98,America/Sao_Paulo,MA
5569,4219853,Zortéa,-27.45210,-51.5520,0,42,950,49,America/Sao_Paulo,SC

In [9]:
def create_state_csv(state_uf, cities_states_df):
    state_folder = os.path.join(f'{base_folder}', state_acronym)
    state_csv_path = os.path.join(state_folder, 'cidades.csv')
    
    state_cities_df = cities_states_df[cities_states_df['uf'] == state_uf]
    state_cities_df.to_csv(state_csv_path, index=False)
    print(f"Criado CSV para cidades o estado {state_uf}: {state_csv_path}")

for state_uf in unique_states:
    create_state_csv(state_acronym, df_cidades_estados)

Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv
Criado CSV para cidades o estado DF: estados/DF/cidades.csv